# Welcome to Serverless!
#
service: g10-a6-serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  codeforces:
    handler: codeforces.scrapeContest
    events:
      - http:
          path: codeforces/contest
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                contestlower: true
                contestupper: true


custom:
  pythonRequirements:
    dockerizePip: true

plugins:
 - serverless-offline
 - serverless-python-requirements
 